# The only current way of using OS X virtual machines in Travis CI
# is setting up a generic environment
# This is not a problem because Python will be installed through conda

language: generic

os:
  - linux
  - osx

env:
  - PYTHON=3.5
  - PYTHON=3.6

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x

before_install:
  - if [[ "$(uname)" == "Darwin" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - if [[ "$(uname)" == "Linux" ]]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # Update conda and create test environment
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python=$PYTHON
  - source activate test-environment

  # Install project requirements
  - conda install numpy numba>=0.23 astropy>=1.0 matplotlib scipy jplephem
  - pip install coverage pytest pytest-cov codecov pytest-benchmark

install:
  - pip install --no-deps .  # Test installation correctness

script:
  - pytest -vv --benchmark-skip  # Test against installed code

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall poliastro -y
  - pip install --no-deps -e .

  - NUMBA_DISABLE_JIT=1 pytest --cov --benchmark-skip

  - codecov

sudo: false
