# The only current way of using OS X virtual machines in Travis CI
# is setting up a generic environment
# This is not a problem because Python will be installed through conda

language: python

branches:
  only:
    - master
    - 0.3.x
    - 0.4.x
    - 0.5.x
    - 0.6.x
    - 0.7.x

env:
  global:
    - MPLBACKEND="Agg"

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy3
      env: PIP_EXTRA_INDEX_URL=https://antocuni.github.io/pypy-wheels/ubuntu/

addons:
  apt:
    packages:
      - pandoc

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then HOMEBREW_NO_AUTO_UPDATE=1 brew install python3; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 -m venv venv; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source venv/bin/activate; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 -m pip install --upgrade pip; fi

install:
  - pip install numpy  # Required
  - pip install .  # Test installation correctness
  - pip install .[dev]  # Test development dependencies

before_script:
  - pep8 setup.py src/  # Check PEP8 compliance
  - mypy --ignore-missing-imports --check-untyped-defs src/  # Check MyPy diagnostics

script:
  - python setup.py test -vv  # Test against installed code
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sphinx-build -vW -b html docs/source _HTMLTest; fi  # Test docs build

after_success:
  # Uninstall to test coverage against sources
  - pip uninstall poliastro -y
  - pip install -e .

  - NUMBA_DISABLE_JIT=1 python setup.py test -a "--cov"

  # Publish coverage
  - pip install codecov
  - codecov

sudo: false
