[build-system]
requires = [
    "flit_core >=2.0,<3",
    "wheel",
    "oldest-supported-numpy",
]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "poliastro"
author = "Juan Luis Cano RodrÃ­guez"
author-email = "hello@juanlu.space"
description-file = "README.rst"
home-page = "https://github.com/poliastro/poliastro/"
keywords = "aero,aerospace,engineering,astrodynamics,orbits,kepler,orbital mechanics"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Astronomy",
]
requires-python = ">=3.7,<3.9"
requires = [
    "astropy >=3.2,<5",
    "astroquery >=0.3.9",
    "cached_property ; python_version<'3.8'",
    "jplephem",
    "matplotlib >=2.0,!=3.0.1",
    "numba >=0.46,!=0.49.0,!=0.49.1 ; implementation_name=='cpython'",  # https://github.com/numba/numba/issues/5661
    "numpy",
    "pandas",
    "plotly ~=4.0",
    "scipy >=1.4.0",
]

[tool.flit.metadata.requires-extra]
jupyter = ["notebook"]
cesium = ["czml3 ~=0.5.3"]
dev = [
    "black",
    "coverage",
    "hypothesis",
    "ipykernel",
    "ipython>=5.0",
    "ipywidgets>=7.0",
    "isort",
    "jupyter-client",
    "mypy>=0.740",
    "nbsphinx>=0.5.0",
    "nbconvert>=5.5",
    "pycodestyle",
    "pytest>=3.2",
    "pytest-cov<2.6.0",  # https://github.com/pytest-dev/pytest-cov/issues/222
    "pytest-doctestplus",
    "pytest-mpl",
    "pytest-mypy",
    "pytest-remotedata",
    "sphinx",
    "sphinx_rtd_theme==0.5.0rc1",
    "sphinx-hoverxref @ https://github.com/readthedocs/sphinx-hoverxref/archive/master.zip",
    "sphinx-notfound-page",
    "tox",
]

[tool.flit.metadata.urls]
Source = "https://github.com/poliastro/poliastro"
Tracker = "https://github.com/poliastro/poliastro/issues"

[tool.flit.entrypoints."console_scripts"]
poliastro = "poliastro.cli:main"

[tool.flit.sdist]
include = [
    "src/poliastro/atmosphere/data/coesa62.dat",
    "src/poliastro/atmosphere/data/coesa76.dat",
    "src/poliastro/atmosphere/data/coesa76_p.dat",
    "src/poliastro/atmosphere/data/coesa76_rho.dat",
    "setup.cfg"
]
