# This workflow triggers poliastro/validation CI from poliastro/poliastro
# everytime a new commit is introduced in poliastro:main branch
name: Validation test cases

on:
  # A collection of events which trigger the validation action
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:

  # Enable manually to execute the actions
  workflow_dispatch:

jobs:
  
  # Validate poliastro's new features
  validation:
    runs-on: ubuntu-latest
    environment: validation-env

    # Steps to be followed during validation job
    steps:
      - name: Trigger poliastro/validation
        shell: bash
        env:
          VALIDATION_USER: ${{ secrets.VALIDATION_USER }}
          VALIDATION_PASS: ${{ secrets.VALIDATION_PASS }}
        run: |
          curl --fail \
          -XPOST -u "$VALIDATION_USER:$VALIDATION_PASS" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/poliastro/validation/actions/workflows/ci_actions.yml/dispatches \
          --data '{"ref":"main"}'
